ALTER TABLE applications
  ALTER COLUMN id SET NOT NULL,
  ALTER COLUMN job_id TYPE INTEGER USING COALESCE(job_id, 0),
  ALTER COLUMN job_id SET NOT NULL,
  ALTER COLUMN applicant_id TYPE INTEGER USING COALESCE(applicant_id, 0),
  ALTER COLUMN applicant_id SET NOT NULL,
  ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE jobs
  ALTER COLUMN company_id TYPE INTEGER USING COALESCE(company_id, 0),
  ALTER COLUMN company_id SET NOT NULL,
  ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE applicants
  ALTER COLUMN created_at SET NOT NULL;